### PR TITLE
Stats url simple

### PR DESCRIPTION
**Pull request by dr4Ke**
Options to use an URL, with authentication if needed, instead of a socket.
I also added mention of known contributors in the copyright notice.

### CODE REVIEW

**Comment by tatref** [comment]
Thanks for the PR!
I'll take a look at your changes and merge it soon.

I'll also add the initial creator. Nagios exchange references the autor's website as entirelyunlike.net (unfortunately, no name provided).

**Comment by dr4Ke** [comment]
I think the original author name is already in there: Giacomo Montagner giacomo@entirelyunlike.net

**Comment by tatref** [comment]
Thanks for the author's name!
Is it possible to try import the LWP module, and not fail if it is not available? From my experience, not all distributions include LWP, and it would be great if people could still use this plugin if they do not wish to install libraries.

**Comment by dr4Ke** [comment]
OK. This commit tries to use `LWP::Simple` if available. Or falls back to the external `curl` command.

**Comment by tatref** [comment]
I works as expected.
Thanks for the quick feedback!

**Pull request merged**
